.PHONY: all
all: build


# Path to custom rustc (derived from CUSTOM_RUSTC_STAGE2 env var)
# If CUSTOM_RUSTC_STAGE2 is not set, this will intentionally expand
# to an invalid path.
CUSTOM_RUSTC_STAGE2 ?= unprovided_path_to_custom_rustc_stage2

CUSTOM_RUSTC_BIN := $(CUSTOM_RUSTC_STAGE2)/bin/rustc
CUSTOM_RUSTC_LIB := $(CUSTOM_RUSTC_STAGE2)/lib

.PHONY: format
format:
	cd charon && $(MAKE) format
	cd charon-ml && $(MAKE) format

# Take the version written in `Cargo.toml` and export it to a ml variable, so
# that charon-ml can error if it is ever given a llbc file with an incompatible
# version.
charon-ml/src/CharonVersion.ml: charon/Cargo.toml
	echo '(* This is an automatically generated file, generated from `charon/Cargo.toml`. *)' > "$@"
	echo '(* To re-generate this file, rune `make` in the root directory *)' >> "$@"
	printf 'let supported_charon_version = ' >> "$@"
	grep '^version =' charon/Cargo.toml | head -1 | sed 's/^version = \(".*"\)/\1/' >> "$@"

# Build the project in release mode, after formatting the code
.PHONY: build
build: build-charon-rust build-charon-ml

# Build in debug mode, without formatting the code
.PHONY: build-dev
build-dev: build-dev-charon-rust build-dev-charon-ml

# Build with custom rustc in release mode
.PHONY: build-custom
build-custom: build-custom-charon-rust build-charon-ml

# Build with custom rustc in dev mode
.PHONY: build-custom-dev
build-custom-dev: build-custom-dev-charon-rust build-dev-charon-ml

.PHONY: build-charon-rust
build-charon-rust:
	cd charon && $(MAKE)
	mkdir -p bin
	cp -f charon/target/release/charon bin
	cp -f charon/target/release/charon-driver bin

.PHONY: build-dev-charon-rust
build-dev-charon-rust:
	cd charon && cargo build
	mkdir -p bin
	cp -f charon/target/debug/charon bin
	cp -f charon/target/debug/charon-driver bin

# Build Charon with custom rustc in release mode
.PHONY: build-custom-charon-rust
build-custom-charon-rust:
	@echo "Building Charon (release) with custom rustc from: $(CUSTOM_RUSTC_BIN)"
	cd charon && \
		RUSTC="$(CUSTOM_RUSTC_BIN)" \
		LD_LIBRARY_PATH="$(CUSTOM_RUSTC_LIB):$$LD_LIBRARY_PATH" \
		RUSTC_BOOTSTRAP=1 \
		CHARON_TOOLCHAIN_IS_IN_PATH=1 \
		CARGO_PROFILE_RELEASE_DEBUG=true \
		cargo build --release
	mkdir -p bin
	cp -f charon/target/release/charon bin
	cp -f charon/target/release/charon-driver bin
	@echo "Done! Use ./scripts/run-charon-with-custom-rustc.sh to run with your custom rustc"

# Build Charon with custom rustc in debug mode
.PHONY: build-custom-dev-charon-rust
build-custom-dev-charon-rust:
	@echo "Building Charon (debug) with custom rustc from: $(CUSTOM_RUSTC_BIN)"
	cd charon && \
		RUSTC="$(CUSTOM_RUSTC_BIN)" \
		LD_LIBRARY_PATH="$(CUSTOM_RUSTC_LIB):$$LD_LIBRARY_PATH" \
		RUSTC_BOOTSTRAP=1 \
		CHARON_TOOLCHAIN_IS_IN_PATH=1 \
		cargo build
	mkdir -p bin
	cp -f charon/target/debug/charon bin
	cp -f charon/target/debug/charon-driver bin
	@echo "Done! Use ./scripts/run-charon-with-custom-rustc.sh to run with your custom rustc"

.PHONY: build-charon-ml
build-charon-ml: charon-ml/src/CharonVersion.ml
	cd charon-ml && $(MAKE)

.PHONY: build-dev-charon-ml
build-dev-charon-ml: charon-ml/src/CharonVersion.ml
	cd charon-ml && $(MAKE) build-dev

# Generate documentation
.PHONY: doc
doc:
	cd charon && $(MAKE) doc
	cd charon-ml && $(MAKE) doc

# Build and run the tests
.PHONY: test
test: clean-generated build-dev charon-tests charon-ml-tests

# Build with custom rustc and run the tests
.PHONY: test-custom
test-custom: clean-generated build-custom-dev charon-tests-custom charon-ml-tests

# Build with custom rustc and run the ui tests
.PHONY: test-ui-custom
test-ui-custom: clean-generated build-custom-dev charon-ui-tests-custom charon-ml-tests

# Run Charon on various test files
.PHONY: charon-tests
charon-tests:
	cd charon && $(MAKE) test

# Run Charon on various test files with custom rustc
.PHONY: charon-tests-custom
charon-tests-custom:
	@echo "Running Charon tests with custom rustc from: $(CUSTOM_RUSTC_BIN)"
	cd charon && \
		RUSTC="$(CUSTOM_RUSTC_BIN)" \
		LD_LIBRARY_PATH="$(CUSTOM_RUSTC_LIB):$$LD_LIBRARY_PATH" \
		RUSTC_BOOTSTRAP=1 \
		CHARON_TOOLCHAIN_IS_IN_PATH=1 \
		$(MAKE) test

# Run Charon ui tests with custom rustc
# TODO(view): Remove `|| true` once all tests pass.
.PHONY: charon-ui-tests-custom
charon-ui-tests-custom:
	@echo "Running Charon ui tests with custom rustc from: $(CUSTOM_RUSTC_BIN)"
	cd charon && \
		RUSTC="$(CUSTOM_RUSTC_BIN)" \
		LD_LIBRARY_PATH="$(CUSTOM_RUSTC_LIB):$$LD_LIBRARY_PATH" \
		RUSTC_BOOTSTRAP=1 \
		CHARON_TOOLCHAIN_IS_IN_PATH=1 \
		cargo test --test ui || true

# Run the Charon ML tests on the .ullbc and .llbc files generated by Charon
.PHONY: charon-ml-tests
charon-ml-tests: build-charon-ml
	cd charon-ml && $(MAKE) tests

# Debug the ocaml tests in `ocamldebug`
.PHONY: debug-ml-tests
debug-ml-tests: build-charon-ml charon-tests
	cd charon-ml && $(MAKE) copy-tests
	rlwrap ocamldebug -cd _build/default/charon-ml/tests/ Tests.bc

# Generate some of the ml code automatically from the rust definitions.
.PHONY: generate-ml
generate-ml:
	cd charon && cargo build --release && cargo run --release --bin generate-ml
	cd charon-ml && $(MAKE) format 2> /dev/null

# Same as `generate-ml` but don't re-run charon on itself. Useful when developping.
.PHONY: generate-ml-keep-llbc
generate-ml-keep-llbc:
	CHARON_ML_REUSE_LLBC=1 $(MAKE) generate-ml

# Generate ml code with custom rustc
.PHONY: generate-ml-custom
generate-ml-custom:
	@echo "Generating ML code with custom rustc from: $(CUSTOM_RUSTC_BIN)"
	cd charon && \
		RUSTC="$(CUSTOM_RUSTC_BIN)" \
		LD_LIBRARY_PATH="$(CUSTOM_RUSTC_LIB):$$LD_LIBRARY_PATH" \
		RUSTC_BOOTSTRAP=1 \
		CHARON_TOOLCHAIN_IS_IN_PATH=1 \
		cargo build --release && \
		RUSTC="$(CUSTOM_RUSTC_BIN)" \
		LD_LIBRARY_PATH="$(CUSTOM_RUSTC_LIB):$$LD_LIBRARY_PATH" \
		RUSTC_BOOTSTRAP=1 \
		CHARON_TOOLCHAIN_IS_IN_PATH=1 \
		cargo run --release --bin generate-ml
	cd charon-ml && $(MAKE) format 2> /dev/null
	@echo "Done! ML code generated with custom rustc"

# Same as `generate-ml-custom` but don't re-run charon on itself
.PHONY: generate-ml-custom-keep-llbc
generate-ml-custom-keep-llbc:
	CHARON_ML_REUSE_LLBC=1 $(MAKE) generate-ml-custom

# Run Charon on rustc's ui test suite
.PHONY: rustc-tests
rustc-tests:
	nix build -L '.#rustc-tests'
	@echo "Summary of the results:"
	@cat result/charon-summary

# Prints a summary of the most common test errors.
.PHONY: analyze-rustc-tests
analyze-rustc-tests: rustc-tests
	find result/ -name '*.charon-output' \
		| xargs cat \
		| grep '^error: ' \
		| sed 's/^error: \([^:]*\).*/\1/' \
		| grep -v 'aborting due to .* error' \
		| sort | uniq -c | sort -h

.PHONY: clean-generated
clean-generated:
	cd charon && $(MAKE) clean-generated

.PHONY: clean
clean: clean-generated
	cd charon && cargo clean
	cd charon/macros && cargo clean
	dune clean

# Build the Nix packages
.PHONY: nix
nix: nix-charon nix-ml

.PHONY: nix-charon
nix-charon:
	nix build .#packages.x86_64-linux.charon --show-trace -L

.PHONY: nix-ml
nix-ml:
	nix build .#checks.x86_64-linux.charon-ml-tests --show-trace -L
